### ISSUE TITLE
gasolinePrice 下的内容没有更新了呀

### ISSUE THREAD

**Issue by 0x24bin** [zqzess/openApiData#1]
从9.6之后就没有更新了

**Comment by zqzess** [comment]
我下午看看

**Comment by 0x24bin** [comment]
大佬，方便问下这个数据从哪里获取的么？

**Comment by zqzess** [comment]
已经更新好了，数据随便找个网站就行，爬虫爬的

**Comment by zqzess** [comment]
忘记说了，最终生成的数据顺序有所变更，以下是变更后的
<img width="514" alt="image" src="https://github.com/user-attachments/assets/6e7376b0-a2dd-4c1e-9929-44610e67e7b5">
<img width="303" alt="image" src="https://github.com/user-attachments/assets/ff07a4a7-15f3-4bf9-938e-78967f213c99">
